spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/w2b
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        max-page-size: 200
        default-page-size: 50
  liquibase:
    change-log: classpath:/db/changelog-master.yaml

logging:
  level:
    liquibase: INFO
