spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/w2b
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
  data:
    web:
      pageable:
        max-page-size: 200
        default-page-size: 50
