INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Pale Ale');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Amber Ale');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Brown Ale');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Strong Ale');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Sour Ale');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Pale Lager');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Amber Lager');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'IPA');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Triple');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Quadruple');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Lambic');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Saison');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Porter');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Stout');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Specialité');
INSERT INTO beer_type (creation_date, last_modified_date, label) VALUES (now(), now(), 'Bière fruitée');

INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'fr', 'France');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'be', 'Belgique');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'ge', 'Allemagne');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'en', 'Angleterre');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'ir', 'Irelande');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'us', 'Etats-Unis');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'sp', 'Espagne');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'ja', 'Japon');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'ca', 'Canada');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'po', 'Portugual');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'pl', 'Pologne');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'ru', 'Russie');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'it', 'Italie');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'br', 'Brésil');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'sw', 'Suisse');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'gr', 'Grece');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'ic', 'Islance');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'no', 'Norvège');
INSERT INTO country (creation_date, last_modified_date, flag, label) VALUES (now(), now(), 'lu', 'Luxembourg');
